### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SiimKirjanen** [bigbite/wp-cypress#66]
**Describe the bug**
Hey. Does this awesome project support Windows? I am trying to run it with Windows 10 + docker desktop (3.3.3) but having problems

**To Reproduce**

When I try to spin up wp-cypress I get the following

![error1](https://user-images.githubusercontent.com/21058594/120095997-c35ad400-c131-11eb-8021-722bf5b36b28.PNG)

Logs show

![error2](https://user-images.githubusercontent.com/21058594/120096009-d077c300-c131-11eb-945e-f39681643a50.PNG)

When I exec into the container I see (no wp-config.php)

![directory](https://user-images.githubusercontent.com/21058594/120096034-e71e1a00-c131-11eb-8559-5e2db1a475cc.PNG)

When I try to access container in browser I get

![install](https://user-images.githubusercontent.com/21058594/120096082-159bf500-c132-11eb-9967-cc2159c5cb11.PNG)

**Expected behavior**

Would be super if I can use Windows.

**Desktop (please complete the following information):**
- OS: Windows 10
- wp-cypress: 0.8.1
- cypress: 7.4.0
- cypress browser: chrome

**Comment by mirkootter** [comment]
I just ran into the same problem and want to use this project, so I decided to look into it. There are several problems, mainly caused by the different command lines. Also this project uses `docker-compose exec` to forward the CLI to the linux container, the command line is parsed on the host.
* Windows does not support Heredoc which is used by the `reset` command
* Windows only supports doublequotes " to scope parameters. Single quotes are just added to the param
* Windows has no special meaning of `$` and escaping `\$` does not work
* To start executables in subdirectories, backslash must be used instead of forward slashes, i.e. `node_modules\.bin\wp-cypress`

I created a pull request to solve there problems:
* Instead of heredoc, I use the pipe feature of `shelljs`. This way, there is no need to escape the `$` character
* Replaced single quotes by double quotes
* use backslash where necessary.
